### ISSUE TITLE
Discrepancy in homework week2

### ISSUE THREAD

**Issue by Akif2709** [HackYourFuture/JavaScript2#286]
There is a differencies about `duration` between  the tables which present on Week2 homework directions and which present on `JavaScript2/Week2/homework/maartjes-work.js`. In the one of them there is `duration: 1.0,` at the other  `duration:200` instead. Also it is incomprehensible if 1.0 refers one hour or one minute.

**Comment by remarcmij** [comment]
Updated MAKEME with the correct values.
