### ISSUE TITLE
Makeme.md

### ISSUE THREAD

**Issue by eneserdek** [HackYourFuture/JavaScript2#288]
In my opinion, the following step should be added in order to prevent misunderstandings.

**1.0** Please download the js documents from 

the following link. You will use and make changes on these documents for the following homeworks. 
(https://github.com/HackYourFuture/JavaScript2/blob/master/Week2/homework)

**Comment by remarcmij** [comment]
Hi @eneserdek, you were supposed to fork this repository, see step 5 here:

https://github.com/HackYourFuture/JavaScript2/blob/master/Week1/README.md#software-installation-for-the-javascript-2-module

When you that you will the starter files you need in your local copy of the repo.

**Comment by remarcmij** [comment]
@eneserdek The files are in the `week2/homework` folder.

**Comment by remarcmij** [comment]
Hi @eneserdek, I'm reopening this issue to not let you miss out on the chance to win the special surprise promised by @wouterkleijn in this slack message:

https://hackyourfuture.slack.com/archives/C0EJMVBPE/p1553417560075100
