### ISSUE TITLE
Refering to non existing chapter numbers

### ISSUE THREAD

**Issue by ArcoMul** [HackYourFuture/JavaScript2#303]
In the section "Design patterns" of the README of week 2 (https://github.com/HackYourFuture/JavaScript2/blob/master/Week3/README.md)

It says: "Learning JavaScript Design Patterns up to and including chapter 3"

The page linked doesn't have any chapter numbers thought: https://addyosmani.com/resources/essentialjsdesignpatterns/book/#detailnamespacing

Or maybe it's just referring to that sub section of the whole page/document. In that case we should maybe clarify that better.

**Comment by wilgert** [comment]
The JavaScript Design Patterns are no longer mentioned in this README. Closing this issue.
