### ISSUE TITLE
Links freecodecamp do not work.

### ISSUE THREAD

**Issue by wouterkleijn** [HackYourFuture/JavaScript2#54]
I tried accessing the freecodecamp challenges in the week 1 makeme.md. [https://github.com/HackYourFuture/JavaScript2/blob/master/Week1/MAKEME.md](url)

 All, except for the last one, seem to have been edited or removed. I will have a look if I can find challenges that can replace these links.

**Comment by remarcmij** [comment]
Updated the links.
