### ISSUE TITLE
Reading Material -- Events 

### ISSUE THREAD

**Issue by JawharBairakdar** [HackYourFuture/JavaScript2#68]
I have seen there is no reading material for the Events in JS2 Week1 I hope this will fit.
https://medium.freecodecamp.org/event-handling-in-javascript-with-examples-f6bc1e2fff57

**Comment by remarcmij** [comment]
Hi @Meno-101, did you intend to include this?

**Comment by Meno-101** [comment]
Hey @remarcmij, At the beginning I thought yes, but this is a very old one, I think now it's a bit confusing thing for a student to read about `Propagation`, `preventDefault`...etc.
Plus after a bit of more experience this article is for who experienced events previously.
